version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: blog_backend
    env_file:
      - ./backend/.env.example
    environment:
      # Override DB to point to the dockerized Postgres service
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog_db
      CORS_ORIGIN: http://localhost:5173
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:4000/api
    container_name: blog_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
